# Generated by Django 3.2.7 on 2022-03-21 00:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import lib.sitestuff


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('news', '0008_newspost_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeAreReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(max_length=6000)),
                ('source', models.URLField()),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_sites', lib.sitestuff.MyManager()),
            ],
        ),
    ]
