# Generated by Django 3.2.7 on 2022-03-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_whatwearereading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatwearereading',
            name='body',
        ),
        migrations.AddField(
            model_name='whatwearereading',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='whatwearereading',
            name='source',
            field=models.CharField(max_length=300),
        ),
    ]
