# Generated by Django 3.2.7 on 2022-03-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20220321_0127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='whatwearereading',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='whatwearereading',
            name='site',
        ),
    ]
