# Generated by Django 3.2.7 on 2022-03-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('news', '0011_auto_20220321_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatwearereading',
            options={'verbose_name': 'What We Are Reading Link', 'verbose_name_plural': 'What We Are Reading Links'},
        ),
        migrations.AddField(
            model_name='whatwearereading',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
