# Generated by Django 3.2.7 on 2022-03-21 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('news', '0012_auto_20220321_0232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='whatwearereading',
            unique_together={('link', 'site')},
        ),
    ]
