# Generated by Django 3.2.7 on 2022-03-21 04:10

from django.db import migrations
import django.db.models.manager
import lib.sitestuff


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_whatwearereading_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='whatwearereading',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_sites', lib.sitestuff.MyManager()),
            ],
        ),
        migrations.RenameField(
            model_name='whatwearereading',
            old_name='published_date',
            new_name='publish_date',
        ),
    ]
