# Generated by Django 3.2.7 on 2021-09-03 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import lib.sitestuff


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('taxonomy', '0002_delete_divesite'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='topic',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_sites', lib.sitestuff.MyManager()),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='site',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
